"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let result = 6 + 2;
console.log(result);
result = 4 * 2;
console.log(result);
result = 16 / 2;
console.log(result);
result = 20 - 12;
console.log(result);
